./ClientMain -t u -i /home/zryang/test_gcc/00-gcc-2.95.0.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/01-gcc-2.95.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/02-gcc-2.95.2.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/03-gcc-2.95.2.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/04-gcc-2.95.3.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/05-gcc-3.0.0.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/06-gcc-3.0.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/07-gcc-3.0.2.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/08-gcc-3.0.3.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/09-gcc-3.0.4.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/10-gcc-3.1.0.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/11-gcc-3.1.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/12-gcc-3.2.0.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/13-gcc-3.2.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/14-gcc-3.2.2.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/15-gcc-3.2.3.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/16-gcc-3.3.0.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/17-gcc-3.3.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/18-gcc-3.3.2.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/19-gcc-3.3.3.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/20-gcc-3.3.4.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/21-gcc-3.3.5.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/22-gcc-3.3.6.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/23-gcc-3.4.0.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/24-gcc-3.4.1.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/25-gcc-3.4.2.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/26-gcc-3.4.3.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/27-gcc-3.4.4.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/28-gcc-3.4.5.tar -m 0
./ClientMain -t u -i /home/zryang/test_gcc/29-gcc-3.4.6.tar -m 0
